apiVersion: v1
kind: Secret
metadata:
  name: sk056-git-repo
  namespace: skala-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: sk056-my-app
  type: git
  url: https://github.com/zinsile/skala-stock-server.git
  username: zinsile
  project: class-2
  # password: "s"
