apiVersion: v1
kind: Service
metadata:
  name: sk056-stock-ingress
  namespace: skala-practice
spec:
  selector:
    app: sk056-skala-stock-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP